-- Your SQL goes here
CREATE TABLE IF NOT EXISTS `comments` (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  article_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE NO ACTION,
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE NO ACTION
);