-- Your SQL goes here
CREATE TABLE IF NOT EXISTS `article_acl` (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  article_id INTEGER NOT NULL,
  pread INTEGER NOT NULL DEFAULT 1,
  pedit INTEGER NOT NULL DEFAULT 4,
  pdelete INTEGER NOT NULL DEFAULT 4,
  prate INTEGER NOT NULL DEFAULT 2,
  pread_rate INTEGER NOT NULL DEFAULT 1,
  prv INTEGER NOT NULL DEFAULT 1,
  pwd INTEGER NOT NULL DEFAULT 1,
  ped INTEGER NOT NULL DEFAULT 1,
  pview_history INTEGER NOT NULL DEFAULT 5,
  pread_comments INTEGER NOT NULL DEFAULT 1,
  pwrite_comments INTEGER NOT NULL DEFAULT 2,
  pedit_comments INTEGER NOT NULL DEFAULT 4,
  pdelete_comments INTEGER NOT NULL DEFAULT 4,
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE NO ACTION
);